### ISSUE TITLE
Run only on Camp

### ISSUE THREAD

**Issue by kenrick95** [pciang/AutobotScript#2]
I think some checking needed to be done such that the script only runs on the Hunter's Camp and not during King's Reward, Login page, nor other pages.

**Comment by pciang** [comment]
@kenrick95 you wanna add it down? http://wiki.greasespot.net/Include_and_exclude_rules

**Comment by pciang** [comment]
seems not that easy with include exclude...

**Comment by kenrick95** [comment]
Try [Ooiks method at its Autobot](http://userscripts-mirror.org/scripts/review/78731) maybe?

**Comment by pciang** [comment]
Yeah, can! You want to implement it?

**Comment by pciang** [comment]
@kenrick95 Hopefully solved!
